# Generated by Django 5.1.6 on 2025-02-25 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'İnceleniyor'), ('resolved', 'Çözüldü')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('Bilgisayar Donanım', 'Bilgisayar Donanım'), ('Bilgisayar Yazılım', 'Bilgisayar Yazılım'), ('Bilgisayar Ağ', 'Bilgisayar Ağ'), ('Telefon Donanım', 'Telefon Donanım'), ('Telefon Batarya', 'Telefon Batarya'), ('Telefon Bağlantı', 'Telefon Bağlantı'), ('Diğer', 'Diğer')], default='Diğer', max_length=50)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='issues/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_fix_time', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
