# Generated by Django 5.1.6 on 2025-02-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_issue_issuecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='estimated_fix_time',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='rating',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(default='Diğer', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(default='medium', max_length=10),
        ),
    ]
