# Generated by Django 5.1.6 on 2025-02-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_issue_resolved_at_issueattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('technician', 'Teknisyen'), ('user', 'Kullanıcı')], default='user', max_length=20),
        ),
    ]
